[tools]
go = "1.24.5"

[tasks.build]
description = "Build the daily binary"
run = "go build -o daily ."

[tasks.dev]
description = "Run the daily CLI in development mode"
run = "go run main.go"

[tasks.lint]
description = "Format code and run static analysis"
run = "go fmt ./... && go vet ./..."