[tools]
go = "1.25.1"
golangci-lint = "latest"
hk = "latest"
"npm:prettier" = "latest"
pkl = "latest"

[tasks.build]
description = "Build the daily binary"
run = "go build -o daily ."

[tasks.dev]
description = "Run the daily CLI in development mode"
run = "go run main.go"

[tasks.lint]
description = "Format code and run static analysis"
run = "go fmt ./... && go vet ./... && golangci-lint run"

[tasks.test]
description = "Test the daily CLI"
run = "go test ./..."

[tasks.test-cov]
description = "Test the daily CLI with Coverage"
run = "go test ./..."