name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Run Linters
        run: |
          mise run lint
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Run Unit Tests
        run: |
          mise run test-cov | tee report.out
          go-junit-report -set-exit-code > tests-report.xml < report.out
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          path: tests-report.xml
